# Generated by Django 4.1.3 on 2022-12-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas_Of_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CallCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublisherBrandName', models.CharField(blank=True, max_length=200)),
                ('callid', models.CharField(blank=True, default='  ', max_length=200)),
                ('sessionid', models.CharField(blank=True, default='  ', max_length=200)),
                ('cc_inbound_transfer_company', models.CharField(blank=True, default='  ', max_length=200)),
                ('cc_inbound_transfer_dba', models.CharField(blank=True, default='  ', max_length=200)),
                ('cc_outbound_company', models.CharField(blank=True, default='  ', max_length=200)),
                ('cc_dba', models.CharField(blank=True, default='  ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Military',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military_status', models.CharField(choices=[('yes', 'yes'), ('No', 'No')], max_length=50)),
                ('military_affiliation', models.CharField(choices=[('Air force', 'Air force'), ('Nevy', 'Nevy')], max_length=50)),
                ('relationship', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Other_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ids', models.CharField(blank=True, default='  ', max_length=200)),
                ('level_of_interest', models.CharField(blank=True, default='  ', max_length=200)),
                ('browser_user_agent', models.CharField(blank=True, default='  ', max_length=200)),
                ('time_zone', models.CharField(blank=True, default='  ', max_length=200)),
                ('device_type', models.CharField(blank=True, default='  ', max_length=200)),
                ('lead_unique_id', models.CharField(blank=True, default='  ', max_length=200)),
                ('web_session_id', models.CharField(blank=True, default='  ', max_length=200)),
                ('site_name', models.CharField(blank=True, default='  ', max_length=200)),
                ('landing_page', models.CharField(blank=True, default='  ', max_length=200)),
                ('supplier_campaign', models.CharField(blank=True, default='  ', max_length=200)),
                ('utm_source', models.CharField(blank=True, default='  ', max_length=200)),
                ('utm_campaign', models.CharField(blank=True, default='  ', max_length=200)),
                ('utm_content', models.CharField(blank=True, default='  ', max_length=200)),
                ('utm_term', models.CharField(blank=True, default='  ', max_length=200)),
                ('utm_supplier_id', models.CharField(blank=True, default='  ', max_length=200)),
                ('utm_sub_id', models.CharField(blank=True, default='  ', max_length=200)),
                ('utm_ad_id', models.CharField(blank=True, default='  ', max_length=200)),
                ('traffic_source_type', models.CharField(blank=True, default='  ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Female', 'F'), ('Male', 'M')], max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('phone2', models.PositiveIntegerField()),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Mxcoo', 'Mxcoo'), ('phoenix', 'phoenix')], max_length=50)),
                ('state', models.CharField(choices=[('Lasca', 'Lasca'), ('MMMMMMXXX', 'MMMMMMXXX')], max_length=50)),
                ('zip_code', models.PositiveIntegerField()),
                ('computer_internet_access', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('hsyear', models.DateTimeField()),
                ('current_education_level', models.CharField(choices=[('High School Diploma', 'High School Diploma'), ('Bachelor Of Science', 'Bachelor Of Science')], max_length=50)),
                ('preferred_education_level', models.CharField(blank=True, choices=[('High School Diploma', 'High School Diploma'), ('Bachelor Of Science', 'Bachelor Of Science')], max_length=50, null=True)),
                ('us_citizen', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('preferred_enrollment', models.CharField(default='0', max_length=10)),
                ('online_or_campus', models.CharField(choices=[('online', 'online'), ('campus', 'campus'), ('either', 'either')], max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('military', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.military')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_complete_enrollment', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('rn_license', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('teaching_certificate', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('is_contacted_by_school', models.BooleanField()),
                ('graduated_in_us', models.BooleanField()),
                ('channel_name', models.CharField(max_length=200)),
                ('ss1', models.PositiveIntegerField()),
                ('ss2', models.CharField(max_length=200)),
                ('ss3', models.CharField(blank=True, default='  ', max_length=200)),
                ('ss4', models.CharField(blank=True, default='  ', max_length=200)),
                ('web_url', models.URLField()),
                ('webinitiatingurl', models.URLField()),
                ('traffic_trustedform_url', models.URLField()),
                ('traffic_jornaya_leadid', models.CharField(max_length=200)),
                ('traffic_trustedform_token', models.CharField(max_length=200)),
                ('traffic_category', models.CharField(choices=[('Education', 'Education'), ('traning', 'traning')], max_length=50)),
                ('supplier_jornaya_leadid', models.CharField(max_length=200)),
                ('supplier_trustedform_token', models.CharField(max_length=200)),
                ('supplier_trustedform_url', models.URLField()),
                ('time_to_call', models.URLField()),
                ('test_flag', models.PositiveIntegerField()),
                ('tcpa_text', models.CharField(default="by checking this box, i agree to be contacted by degreesearch and the schools i\\'''m matched to on the following pages by telephone, which may include artificial or pre-recorded calls and/or sms text messages, delivered via automated technology to the phone number that i have provided above regarding educational opportunities. i also represent that i am the subscriber and primary user of the telephone that i have provided above. i understand that my consent is not required to make a purchase or obtain services and that i may opt-out at any time. in order to proceed without providing consent, call 401-396-0389.", max_length=1000)),
                ('areas_of_interest', models.ManyToManyField(to='mainapp.areas_of_interest')),
                ('callcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.callcenter')),
            ],
        ),
        migrations.CreateModel(
            name='SearchConnected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.other_info')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.prospect')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.search')),
            ],
        ),
    ]
